<div class="fond-perdu"></div>
<div class="container">
    <section class="about">
        <h1 class="text-center"><?=$topUser['use_firstname']?> <?=$topUser['use_lastname']?></h1>
        <div class="parent-avatar"><figure class="avatar" style="background-image:url(<?=$avatar?>)"></figure></div>
        <div class="user-description"><?=$topUser['use_description']?></div>

        <div class="flex justify-center">
            <a href="/realisations" class="btn btn-blue">Projets</a>
            <a href="/services" class="btn btn-blue">Services</a>
        </div>
    </section>
</div>