<a href="bannerAdd.php" class="btn btn-primary mb-3"><i class="fas fa-plus pr-1"></i> Ajouter une photo de bannière</a>

<div id="myCarousel" class="carousel slide col-xl-6 col-sm-12 m-auto" data-bs-ride="carousel">
  <div class="carousel-inner ">
    <div class="carousel-item active">
      <?php if ($picture1 !== false) :?>
        <img src="../uploads/banner/<?=$picture1['ban_picture']?>" class="d-block w-100">
      <?php else:?>
        <img src="../uploads/services/default-image-test.png" class="d-block w-100">
      <?php endif;?>
    </div>
    <div class="carousel-item">
      <?php if ($picture2 !== false) :?>
        <img src="../uploads/banner/<?=$picture2['ban_picture']?>" class="d-block w-100">
      <?php else:?>
       <img src="../uploads/services/default-image-test.png" class="d-block w-100">
      <?php endif;?>
    </div>
    <div class="carousel-item">
      <?php if ($picture3['ban_picture'] !== 'empty') :?>
        <img src="../uploads/banner/<?=$picture3['ban_picture']?>" class="d-block w-100">
      <?php else:?>
       <img src="../uploads/services/default-image-test.png" class="d-block w-100">
      <?php endif;?>
    </div>
  </div>
</div>



  <form action ="" method="POST">
  <div class="row ml-0 d-flex justify-content-xl-start justify-content-center mt-5">
    <?php foreach($banners as $banner): ?>
        
      <div class="pr-4 position-relative">
          <div class="position-absolute" style="z-index:1;">
              <a href="#" data-toggle="modal" data-target="#banner-<?=$banner['ban_id']?>" class="btn btn-danger"><i class="fas fa-window-close"></i></a>
          </div>
          <div class="card" style="width: 18rem;">
              <?php if ($banner['ban_picture'] !== 'empty') :?>
                <img src="../uploads/banner/<?=$banner['ban_picture'] ?>" class="d-block w-100">
              <?php else:?>
              <img src="../uploads/services/default-image-test.png" class="d-block w-100">
              <?php endif;?>
              <div class="card-body">
                  <!-- TITRE -->
                  <h3 class="card-title text-center"><?=$banner['ban_title']?></h3>
                  <!-- ORDRE AFFICHAGE -->
                  
                  <p class="mb-1 pt-2">Ordre d'affichage</p>
                  <select class="custom-select text-center p-2 mb-4" id="display" name="displayNumber-<?=$banner['ban_id'] ?>">
                    <option value="null" selected>Choisir un chiffre</option>
                    <option value="1"<?php if ($banner['ban_display'] == 1) :?> selected <?php endif;?>>1</option>
                    <option value="2" <?php if ($banner['ban_display'] == 2) :?> selected <?php endif;?>>2</option>
                    <option value="3" <?php if ($banner['ban_display'] == 3) :?> selected <?php endif;?>>3</option>
                  </select>
                  <!-- BOUTON MODIFIER -->
                  <a href="bannerAdd.php?id=<?=$banner['ban_id'] ?>" class="btn btn-primary"><i class="fas fa-edit pr-1"></i>MODIFIER</a>

              </div>
          </div>
      </div>

      <!-- Modal de suppression -->
      <?php if($_SESSION['user']['use_role'] !== 'ROLE_ADMIN') :?>
          <div class="modal fade" id="banner-<?=$banner['ban_id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
              <div class="modal-dialog">
                  <div class="modal-content">
                      <div class="modal-header">
                          <h5 class="modal-title text-danger" id="exampleModalLabel">Désolé...</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                          </button>
                      </div>
                      <div class="modal-body">
                          Vous n'avez <b>pas les droits</b> pour supprimer une photo de bannière.
                      </div>
                      <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                      </div>
                  </div>
              </div>
          </div>
      <?php else :?>
        <div class="modal fade" id="banner-<?=$banner['ban_id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-danger" id="exampleModalLabel">Attention</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Êtes-vous sûr de vouloir supprimer la photo <b><?=$banner['ban_title']?></b>?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                        <input type="hidden" name="title-<?=$banner['ban_id']?>" value="<?=$banner['ban_title']?>"/>
                        <input type="hidden" name="picture-<?=$banner['ban_id']?>" value="<?=$banner['ban_picture']?>"/>
                        <button type="submit" name="<?=$banner['ban_id']?>" class="btn btn-danger" value="<?=$banner['ban_id']?>">Supprimer</button>
                    </div>
                </div>
            </div>
        </div>
      <?php endif ;?>
    <?php endforeach ?>
    </div>
    <button type="submit" class="btn btn-success text-white mt-3" name="order" value="order"><i class="fas fa-check pr-1"></i> Changer l'ordre</button>
  </form>
