
<div class="row">
    <div class="col-lg-4 col-sm-6 col-xs-12">
        <div class="white-box analytics-info">
            <h3 class="box-title">Emails reçus</h3>
            <div class="row box-info">
                <div class="col">
                    <i class="fa fa-chart-bar text-success"></i>
                </div>
                <div class="col">
                    <span class="counter text-success d-flex justify-content-end"><?=$contactCount?></span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6 col-xs-12">
        <div class="white-box analytics-info">
            <h3 class="box-title">Nombre de projets</h3>
            <div class="row box-info">
                <div class="col">
                    <i class="fa fa-briefcase text-purple"></i>
                </div>
                <div class="col">
                    <span class="counter text-purple d-flex justify-content-end"><?=$projectCount?></span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6 col-xs-12">
        <div class="white-box analytics-info">
            <h3 class="box-title">Nombre de services</h3>
            <div class="row box-info">
                <div class="col">
                    <i class="fa fa-bolt text-info"></i>
                </div>
                <div class="col">
                    <span class="counter text-info d-flex justify-content-end"><?=$serviceCount?></span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-8 col-md-12">
        <div class="white-box">
            <h3 class="box-title pb-2">Notes</h3>
            <article class="notes">
                <h4>Services</h4>
                <p>Il faut faire attention à la longueur du 2eme et du 5eme. De manière générale les 6 premiers doivent être assez concis.</p>
            </article>
            <article class="notes">
                <h4>Insérer une image</h4>
                <p>Petite astuce pour insérer une image dans les blocs de texte : Il faut copier l'image depuis google ou depuis un hebergeur d'image en ligne (exemple sur <a href="https://imageshack.com/" target="blank">imageshack</a>)</p>
            </article>
            <article class="notes">
                <h4>Pour resizer une image</h4>
                <p>"clique droit" sur l'image -> "image" -> modifier la width(largeur) et la height (hauteur). Sinon clique gauche sur l'image puis on se sert du cadre bleu en selectionnant les ancres dans les coins.</p>
            </article>
            <article class="notes">
                <h4>Intégration des vidéos</h4>
                <p>Sur youtube il faut cliquer sur "partager" puis sur "intégrer" et copier la balise "iframe" dans le bloc de texte.</p>
                <p>Attention : Pour une raison mystérieuse il y a une astuce pour qu'elles s'affichent correctement sur le front :</p>
                <p>Il faut un espace avant et après. Il est possible de les supprimer par la suite.</p>
            </article>
        </div>
    </div>
</div>