<form action="" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">

    <div class="col-lg-12 col-xlg-9 col-md-12 pt-4 d-block m-auto">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="form-group col-md-6 pb-4 mb-0 text-center">
                        <label for="title">Titre</label>
                        <div class="border-bottom p-0 MT-2">
                            <input type="text" name="title" id="title" value="<?=$title?>" class="form-control pl-2 border-0 text-center" style="font-size:20px"/>
                        </div>
                        <?php if(!empty($errors) && isset($errors['title'])):?>
                            <p class="text-danger mb-0 pt-1"><?=$errors['title']?></p>
                        <?php endif ?>
                    </div>
                    <div class="col-md-3"></div>

                    <div class="form-group col-md-12 pb-3 mb-0">
                        <label for="description">Description du projet</label>
                        <div class="col-md-12 border-bottom p-0">
                            <textarea class="form-control" name ="description" id="description" rows="6" style="height: 300px;"><?=$description?></textarea>
                        </div>    
                        <?php if(!empty($errors) && isset($errors['description'])):?>
                            <p class="text-danger mb-0 pt-1"><?=$errors['description']?></p>
                        <?php endif ?>
                    </div>
                    <?php if($count['hom_count'] !== '0') :?>
                        <div class="w-100 text-center pt-2">
                            <label class="pr-2 text-danger" for="deleteIntro">Supprimer le texte d'introduction ?</label>
                            <input class="form-check-input ml-0" type="checkbox" id="deleteIntro" name="deleteIntro" value="<?=$deleteIntro?>">
                        </div>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
    
    <?php if ($count['hom_count'] === '0') : ?>
        <button type="submit" class="btn btn-primary d-block m-auto">AJOUTER</button>
    <?php else : ?>
        <button type="submit" class="btn btn-success d-block m-auto text-white">MODIFIER</button>
    <?php endif; ?>

</form>