
    <div class="error-body text-center">
        <h1 class="error-title text-danger">404</h1>
        <h3 class="text-uppercase error-subtitle">IMPOSSIBLE DE CHARGER LA PAGE</h3>
        <p class="text-muted m-t-30 m-b-30">Il n'y a pas d'utilisateur classé "top". Créez-en un pour avoir accès à cette page</p>
        <a href="userAdd.php" class="btn btn-danger btn-rounded waves-effect waves-light m-b-40">Ajout d'utilisateur</a>
    </div>
