
<?php if ($count == 0) :?>
    <div class="error-body text-center">
        <h1 class="error-title text-danger">404</h1>
        <h3 class="text-uppercase error-subtitle">IMPOSSIBLE DE CHARGER LA PAGE</h3>
        <p class="text-muted m-t-30 m-b-30">Il n'y a pas encore de projets créés. Créez-en un pour avoir accès à cette page</p>
        <a href="projectAdd.php" class="btn btn-danger btn-rounded waves-effect waves-light m-b-40">Ajouter un projet</a>
    </div>
<?php else :?>
    <a href="projectList.php" class="btn btn-secondary mb-2"><i class="fas fa-arrow-alt-circle-left pr-1"></i>Retour à la liste des projets</a>
    <form action="" method="POST" class="form-horizontal form-material">
        <input type="hidden" name="formsubmit" value="yes" />
        <div class="row">
            <?php foreach($projects as $project): ?>
                
                    <div class="col-lg-4 col-md-6 pt-4">
                        <div class="card mb-2">
                            <div class="card-body p-4 d-flex justify-content-between align-items-center">
                                <div class=" col-lg-4 mb-0 p-0 w-50">
                                    <h5 class="mb-0"><?=$project['pro_title']?></h5>
                                </div>
                                <div class="col-lg-3 mb-0 p-0  w-50">
                                    <select class="custom-select text-center p-2" id="display" name="displayNumber-<?=$project['pro_id'] ?>">
                                        <option value="1" <?php if ($project['pro_display'] == 1) :?> selected <?php endif;?>>1</option>
                                        <option value="2" <?php if ($project['pro_display'] == 2) :?> selected <?php endif;?>>2</option>
                                        <option value="3" <?php if ($project['pro_display'] == 3) :?> selected <?php endif;?>>3</option>
                                        <option value="4" <?php if ($project['pro_display'] == 4) :?> selected <?php endif;?>>4</option>
                                        <option value="5" <?php if ($project['pro_display'] == 5) :?> selected <?php endif;?>>5</option>
                                        <option value="6" <?php if ($project['pro_display'] == 6) :?> selected <?php endif;?>>6</option>
                                        <option value="7" <?php if ($project['pro_display'] == 7) :?> selected <?php endif;?>>7</option>
                                        <option value="8" <?php if ($project['pro_display'] == 8) :?> selected <?php endif;?>>8</option>
                                        <option value="9" <?php if ($project['pro_display'] == 9) :?> selected <?php endif;?>>9</option>
                                        <option value="10" <?php if ($project['pro_display'] == 10) :?> selected <?php endif;?>>10</option>
                                        <option value="11" <?php if ($project['pro_display'] == 11) :?> selected <?php endif;?>>11</option>
                                        <option value="12" <?php if ($project['pro_display'] == 12) :?> selected <?php endif;?>>12</option>
                                        <option value="13" <?php if ($project['pro_display'] == 13) :?> selected <?php endif;?>>13</option>
                                        <option value="14" <?php if ($project['pro_display'] == 14) :?> selected <?php endif;?>>14</option>
                                        <option value="15" <?php if ($project['pro_display'] == 15) :?> selected <?php endif;?>>15</option>
                                    </select>
                                    <?php if(!empty($errors) && isset($errors['display'])):?>
                                        <p class="text-danger mb-0 pt-1"><?=$errors['display']?></p>
                                    <?php endif ?>
                                </div>
                            </div>
                        </div>
                    </div>
                
            <?php endforeach ?>
            </div>
        <button type="submit" class="btn btn-success text-white mt-3"><i class="fas fa-check pr-1"></i> OK !</button>
    </form>
<?php endif ;?>