<a href="serviceList.php" class="btn btn-secondary mb-3"><i class="fas fa-arrow-alt-circle-left pr-1"></i>Annuler</a>

<form action="" id="file-upload-form" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">
<div class="row">

    <div class="col-lg-4 col-xlg-3 col-md-12">
        <label class="col-md-12 pl-0 h3 text-primary text-center mb-2 pr-0" for="picture">Photo</label>
            <div class="parent-div d-flex justify-content-center position-relative">
                <input type="file" name="picture" id="file-upload" class="pointer" data-max-files="1" style="position:absolute;top:0;left:0;opacity:0"/>
                <span id="file-upload-btn" class="btn btn-primary"><i class="fa fa-download text-white pr-2" aria-hidden="true"></i>Drag or browse</span>
            </div>    
            <div class="form-group col-md-12 py-2 mb-0">
                <label for="file-upload" id="file-drag" class="d-flex justify-content-center">
                    <!-- EDITION : si on a une photo on l'affiche et on passe le nom de cette photo dans un champ caché ! -->
                    <?php if($oldPicture !== null) :?>
                        <input type="hidden" name="oldPicture" value="<?=$oldPicture?>">
                        <img id="file-image" src="../uploads/services/<?=$oldPicture?>" class="hidden pt-2 d-block m-auto">
                    <?php else:?>
                        <img id="file-image" src="../uploads/services/default-image-test.png" class="hidden pt-2 d-block m-auto">
                    <?php endif;?>
                    <div class="position-relative">
                        <div id="start" style="left: 0; top: 0; opacity: 0; position: absolute;">
                            <i class="fa fa-download" aria-hidden="true"></i>
                            <div></div>
                            <span id="file-upload-btn" class="btn btn-primary"></span>
                            <div id="notimage" class="hidden"></div>
                        </div>
                        <div id="response" class="hidden" style="opacity:0;display:none">
                            <div id="messages"></div>
                            <progress class="progress" id="file-progress" value="0">
                                <span>0</span>%
                            </progress>
                    </div>
                </label>
            </div>
        </div>
        <div class="parent-div d-flex justify-content-center flex-wrap">
                <?php if($oldPicture !== null) :?>
                    <div class="w-100 text-center pt-2">
                        <label class="pr-2 text-danger" for="deletePicture">Supprimer la photo ?</label>
                        <input class="form-check-input ml-0" type="checkbox" id="deletePicture" name="deletePicture" value="<?=$deletePicture?>">
                    </div>
                <?php endif;?>
                <p class="form-text text-center text-primary">Pour modifier une image téléchargez en une nouvelle. Sinon l'ancienne sera conservée !</p>
                <?php if(!empty($errors) && isset($errors['picture'])):?>
                    <p class="text-danger mb-0"><?=$errors['picture']?></p>
                <?php endif ?>
            </div>
    </div>

    <div class="col-lg-8 col-xlg-9 col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="form-group col-md-12 pb-4 mb-0">
                    <label for="title">Titre</label>
                    <div class="col-md-6 border-bottom p-0">
                        <input type="text" name="title" id="title" value="<?=$title?>" class="form-control pl-2 border-0"/>
                    </div>
                    <?php if(!empty($errors) && isset($errors['title'])):?>
                        <p class="text-danger mb-0 pt-1"><?=$errors['title']?></p>
                    <?php endif ?>
                </div>

                <div class="form-group col-md-12 pb-4 mb-0">
                <label for="description">Description du service</label>
                    <div class="col-md-12 border-bottom p-0">
                        <textarea class="form-control" name ="description" id="description" rows="6" style="height: 300px;"><?=$description?></textarea>
                    </div>    
                    <?php if(!empty($errors) && isset($errors['description'])):?>
                        <p class="text-danger mb-0 pt-1"><?=$errors['description']?></p>
                    <?php endif ?>
                </div>

                <div class="form-group col-md-6 pb-4 mb-0">
                    <label for="price">Prix</label>
                    <div class="col-md-6 border-bottom p-0 input-group">
                        <input type="text" name="price" id="price" value="<?=$price?>" class="form-control pl-2 border-0"/>
                        <span class="input-group-text" id="basic-addon1">€</span>
                    </div>
                    <?php if(!empty($errors) && isset($errors['price'])):?>
                        <p class="text-danger mb-0 pt-1"><?=$errors['price']?></p>
                    <?php endif ?>
                </div>

                <div class="form-group col-md-12 pb-4">
                    <div class="w-100">
                        <label class="pr-2" for="top">Service classé top ?</label>
                        <input class="form-check-input ml-0" type="checkbox" id="top" name="top" value="<?=$top?>"
                        <?php if ($top ==  1):?> checked <?php endif;?>>
                    </div>
                    <small class="text-secondary">Les services classés "top" seront ceux affichés sur la page d'accueil</small>
                </div>
                
                <div class="form-group col-md-4 mb-0">
                    <label for="display">Afficher le service en position</label>
                        <div class="col-md-6 border-bottom p-0">
                        <input type="number" name="display" id="display" min="1" max="50" value="<?=$display?>" class="form-control pl-2 border-0" required/>
                    </div>
                    <?php if(!empty($errors) && isset($errors['display'])):?>
                        <p class="text-danger mb-0 pt-1"><?=$errors['display']?></p>
                    <?php endif ?>
                    
                </div>
                <div class="form-group col-md-6 pb-4 mb-0">
                <?php if($display == null):?>
                        <small class="text-secondary">Pour info tu as déjà <?=$count['ser_count']?> service(s). Ordre suggéré : <?=$count['ser_count']+1?></small>
                <?php endif ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-xlg-3 col-md-12"></div>
    <div class="col-lg-8 col-xlg-9 col-md-12">
    <button type="submit" class="btn btn-primary"><?php if (is_null($id)) : ?>AJOUTER<?php else : ?>MODIFIER<?php endif; ?></button>
    </div>
    
</div>

