

<a href="serviceAdd.php" class="btn btn-primary mb-3"><i class="fas fa-plus pr-1"></i> Ajouter un service</a>
<a href="serviceDisplay.php" class="btn btn-primary mb-3"><i class="fas fa-list pr-1"></i> Modifier l'ordre</a>

<div class="row ml-0 d-flex justify-content-xl-start justify-content-center">
<?php foreach($services as $service): ?>
    
        <div class="pr-4 position-relative">
            <div class="position-absolute" style="z-index:1;">
                <a href="#" data-toggle="modal" data-target="#service-<?=$service['ser_id']?>" class="btn btn-danger"><i class="fas fa-window-close"></i></a>
            </div>
            <div class="card" style="width: 18rem;">
                <?php if ($service['ser_picture'] === null): ?>
                    <img src="../uploads/services/default-image.png" class="card-img-top">
                <?php else :?>
                    <img src="../uploads/services/<?=$service['ser_picture'] ?>" class="card-img-top">
                <?php endif ;?>
                
                
                <div class="card-body">
                    <h5 class="card-title"><?=$service['ser_title']?></h5>
                    <p class="card-text"><?=$service['ser_price']?></p>
                    <a href="serviceAdd.php?id=<?=$service['ser_id'] ?>" class="btn btn-primary"><i class="fas fa-edit pr-1"></i>MODIFIER</a>
                    <?php if ($service['ser_top'] == 1): ?>
                        <a class="btn btn-warning"><i class="fas fa-star pr-1"></i>TOP</a>
                    <?php endif ;?>
                </div>
            </div>
        </div>

        <!-- Modal de suppression -->
        <?php if($_SESSION['user']['use_role'] !== 'ROLE_ADMIN') :?>
            <div class="modal fade" id="service-<?=$service['ser_id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title text-danger" id="exampleModalLabel">Désolé...</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Vous n'avez <b>pas les droits</b> pour supprimer un service.
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                        </div>
                    </div>
                </div>
            </div>
        <?php else :?>
            <form action ="serviceDelete.php" method="POST">
                <div class="modal fade" id="service-<?=$service['ser_id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-danger" id="exampleModalLabel">Attention</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Êtes-vous sûr de vouloir supprimer le service <b><?=$service['ser_title']?></b>?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                                <input type="hidden" name="title-<?=$service['ser_id']?>" value="<?=$service['ser_title']?>"/>
                                <input type="hidden" name="picture-<?=$service['ser_id']?>" value="<?=$service['ser_picture']?>"/>
                                <button type="submit" name="<?=$service['ser_id']?>" class="btn btn-danger" value="<?=$service['ser_id']?>">Supprimer</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        <?php endif ;?>
<?php endforeach ?>
</div>