<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <script src="https://kit.fontawesome.com/73ab01ebea.js" crossorigin="anonymous"></script>
        <title>Reinitialisation</title>
        
        <script src="https://kit.fontawesome.com/73ab01ebea.js" crossorigin="anonymous"></script>
        <!-- Bootstrap CSS -->
	      <link rel="stylesheet" href="css/style.min.css">
        <link rel="stylesheet" href="css/log.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="../css/icons.css">
    </head>
    <body>
        <form class="form-signin"  method="POST" >
        <input type="hidden" name="token" value="<?=$_SESSION['token']?>">
        <?php if($tokenError == false) :?>
          <?php if($displayConfirmation == false) :?>
          <h1 class="text-center pb-3">Réinitialisation</h1>
            <div class="form-group">
              <label for="email">Email</label>  
              <input type="email" class="form-control" name ="email" id="email" value="<?=$_SESSION['userMail']?>">
              <?php if(!empty($errors) && isset($errors['email'])):?>
                  <p class="text-danger mb-0 pt-1"><?=$errors['email']?></p>
              <?php endif ?>
            </div>
            <div class="form-group">
              <label for="password">Nouveau mot de passe</label>
              <input type="password" class="form-control" id="password" name="password" placeholder="Mot de passe">
              <?php if(!empty($errors) && isset($errors['password'])):?>
                  <p class="text-danger mb-0 pt-1"><?=$errors['password']?></p>
              <?php endif ?>
            </div>
            <div class="form-group mb-0">
              <label for="confirmPassword">Confirmation du mot de passe</label>
              <input type="password" class="form-control" id="confirmPassword" name="confirmPassword" placeholder="Confirmation">
            </div>
            <?php if(!empty($errors) && isset($errors['confirmPassword'])):?>
                <p class="text-danger mb-0 pt-1"><?=$errors['confirmPassword']?></p>
            <?php endif ?>
                <button type="submit" class="btn btn-primary buttonLayout" name="update">Envoyer</button>
          <?php else :?>
              <p class="text-success text-center w-100 mt-3"><i class="fas fa-check pr-1"></i>Mot de passe mis à jour !</p>
              <div class="d-flex justify-content-center mb-3"><a class="btn btn-primary" href="login.php">Accéder au login</a></div> 
          <?php endif;?>
        <?php else :?>
          <h3 class="text-danger text-center w-100 mt-3">Mauvais lien.</h3>
          <p class="text-center w-100 mt-3">Utilises le <b>dernier lien reçu</b> dans tes mails !</p>
        <?php endif;?>
          
        </form>

        <!-- Option 1: jQuery and Bootstrap Bundle -->
        <script src="plugins/bower_components/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap tether Core JavaScript -->
        <script src="bootstrap/dist/js/bootstrap.min.js"></script>
    </body>
</html>
