<!-- CODE HTML SPECIFIQUE A LA PAGE USER LIST -->

<div class="table-responsive-md mt-4 all">
    <a href="userAdd.php" class="btn btn-primary mb-3"><i class="fas fa-plus pr-1"></i> Ajouter un utilisateur</a>
    <table class="table table-striped ">
    	<thead>
            <tr>
            <th class="text-center" scope="col">ID</th>
            <th scope="col">Prénom</th>
            <th scope="col">Nom</th>
            <th scope="col">Email</th>
            <th scope="col">Rôle</th>
            <th scope="col" class="text-center">Top</th>
            <th scope="col" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
          
        
        <?php foreach($users as $user): ?>
            <tr>
                <td class="text-center"><?=$user['use_id']?></td>
                <td><?=$user['use_firstname']?></td>
                <td><?=$user['use_lastname']?></td>
                <td><?=$user['use_email']?></td>
                <td>
                    <?php if ($user['use_role'] == 'ROLE_ADMIN') : ?> Admin
                    <?php elseif ($user['use_role'] == 'ROLE_USER') : ?> Utilisateur
                    <?php endif ?>
                </td>
                <td class="text-center">
                    <?php if ($user['use_top'] == 1) : ?> <i class="fas fa-star pr-1 text-warning">
                    <?php elseif ($user['use_top'] == 0) : ?> -
                    <?php endif ?>
                </td>
                <td class="text-center">
                    <a href="#" data-toggle="modal" data-target="#user-<?=$user['use_id']?>"><i class="fa fa-trash text-danger mr-2 h5"></i></a>
                    <a href="userAdd.php?id=<?=$user['use_id'] ?>"i class="fa fa-edit text-secondary mr-2 h5"></i></a>
                </td>
            </tr>
            <!-- Modal de suppression -->
            <?php if($_SESSION['user']['use_role'] !== 'ROLE_ADMIN') :?>
                <div class="modal fade" id="user-<?=$user['use_id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-danger" id="exampleModalLabel">Désolé...</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Vous n'avez <b>pas les droits</b> pour supprimer un compte.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php else :?>
                <form action ="userDelete.php" method="POST">
                    <div class="modal fade" id="user-<?=$user['use_id']?>" tabindex="-1" aria-labelledby="supprimer" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title text-danger" id="exampleModalLabel">Attention</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <?php if($user['use_email'] == $_SESSION['user']['use_email']) :?>
                                <div class="modal-body">
                                    Vous êtes sur le point de supprimer <b>votre compte</b>.<br>
                                    Si vous cliquez sur "supprimer" vous serez déconnecté !
                                </div>
                                <?php else :?>
                                <div class="modal-body">
                                    Êtes-vous sûr de vouloir supprimer l'utilisateur <b><?=$user['use_firstname']?></b>?
                                </div>
                                <?php endif ?>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                                    <input type="hidden" name="name-<?=$user['use_id']?>" value="<?=$user['use_firstname']?>"/>
                                    <input type="hidden" name="picture-<?=$user['use_id']?>" value="<?=$user['use_avatar']?>"/>
                                    <button type="submit" name="<?=$user['use_id']?>" class="btn btn-danger" value="<?=$user['use_id']?>">Supprimer</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            <?php endif ?>
        <?php endforeach ?>

      </tbody>
    </table>
</div>



